# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=b'pic_folder/None/no-img.jpg', upload_to=b'pic_folder'),
        ),
    ]
