# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import member.models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20160321_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default=b'default.jpg', upload_to=member.models.getImageLocation),
        ),
    ]
