# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 01:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genderPreference',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='surveyScore',
            field=models.IntegerField(default=0),
        ),
    ]
