# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-07 08:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20160407_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phoneNumber',
            field=models.CharField(default=b'000-000-0000', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 7, 1, 56, 28)),
        ),
    ]
